### ISSUE TITLE
How to get queue name from bean?

### ISSUE THREAD

**Issue by andycui66** [budjb/grails-rabbitmq-native#105]
Maybe this is asked somewhere. I tried google and stackoverflow but could not find an answer.

I have a bean defined in resources.groovy
`<bean id="queueName" class="java.lang.String">
    <constructor-arg value="mySpecialQueueName"/>
</bean>`

How can I use that bean as the queue name in my consumer? I tried the following code but getting a MissingPropertyException
`static rabbitConfig = [
            "queue": getQueue()
    ]  `
 `static getQueue() {
        return Holders.applicationContext.queueName
    }`

**Comment by budjb** [comment]
The plugin does not support loading a configuration from a bean. This is something that works with spring-amqp.

What you can do is utilize the central consumer configuration functionality in the plugin. See the documentation for details.
