### ISSUE TITLE
waitForConfirmsOrDie 

### ISSUE THREAD

**Issue by scott-seo** [budjb/grails-rabbitmq-native#34]
I would like to be able to call 

channel.waitForConfirmsOrDie() 

Here is an example of its usage
http://hg.rabbitmq.com/rabbitmq-java-client/file/default/test/src/com/rabbitmq/examples/ConfirmDontLoseMessages.java

Current workaround is obtaining RabbitContext and creating the channel manually. Then call waitForConfirmsOrDie().

It would be nice to have this method opened up as apart of RabbitMessageBuilder API.

Thank you for creating this project. It's concise and simple. However, I still feel that I have full access to native RabbitMQ client API library.

**Comment by budjb** [comment]
Are confirms useful without the use of ConfirmListeners?

**Comment by budjb** [comment]
This functionality has been added to the 3.1 release.
