### ISSUE TITLE
RabbitMQ Dynamic Connection

### ISSUE THREAD

**Issue by sujaisd** [budjb/grails-rabbitmq-native#38]
Is there a way to connect to a RabbitMQ server, without adding host/credentials in the config file.

I would like to add those configuration to database and later connect them after a specific activity.
The entire config initialisation should be happening by picking values from DB.

**Comment by budjb** [comment]
The ability to disable the plugin has been added as of 3.0.3.  The functionality will register all of the required beans, but prevent anything from starting.

I'd suggest setting enabled to false, and in your bootstrap modify the grails config with your own supplied values, and then start the plugin.
