### ISSUE TITLE
RPC doesn't allow for connecting to queues

### ISSUE THREAD

**Issue by mgkimsal** [budjb/grails-rabbitmq-native#39]
Whenever I try to send an RPC to a queue (using the 'routingKey', and having no exchange referenced), the request simply times out.  

Is it not possible to RPC to a queue?  Is it an 'exchange-only' concept?

**Comment by budjb** [comment]
I wrote a test case for this, and the application behaved as expected.  I set the routing key to the queue's name, and the queue received it and responded back as expected.
