### ISSUE TITLE
factory.automaticRecovery exceeds access rights

### ISSUE THREAD

**Issue by simoncomley** [budjb/grails-rabbitmq-native#42]
Hi,

I'm getting a compilation error when trying to boot up my application and it appears to be down to line 175 of ConnectionContext.groovy where you are attempting to set a private variable:

factory.automaticRecovery = automaticReconnect

Am I missing something here or is it a bug? When I hack it and comment out the line the application boots up just fine.

**Comment by budjb** [comment]
Actually, this should not be private.  The error you're receiving isn't related to the modification of a private member anyway; it just says that the property does not exist.  This has worked in a production deployment for quite a while, so I'm going to close this issue out.
