### ISSUE TITLE
java client 10 releases out of date - request upgrade to current release

### ISSUE THREAD

**Issue by jwilcox1028** [budjb/grails-rabbitmq-native#45]
I am evaluating this plugin and noticed right away that your config file shows you are stilling using 3.3.0 rabbitmq java client in your current release which appears to be 10 releases behind.

Can you please respond with whether this is intentional, and when you plan to get this back on track or closer to the current 3.4.3 release? I imagine a new release is in the works soon?

Also you appear to be the only major grails rabbitmq plugin with good code support ongoing which I commend. Can you tell me how committed this project is to continuing forward as we would be adding this plugin in to a major enterprise class project requiring support for quite some time.

**Comment by budjb** [comment]
We use this on my team's projects at my employer.  As I find things that need fixing, I get them fixed.

I haven't had a reason to update the RabbitMQ library version, which is the only reason it's not updated.  It shouldn't be too big a deal to update it.  I have an outstanding feature pull request, so I'll likely bump the version when I merge that code in.

**Comment by budjb** [comment]
Just an update, the upcoming version 3.1.X of the plugin upgrades the library to 3.5.0.
