### ISSUE TITLE
RabbitConsumer fails to send RPC without indication of failure

### ISSUE THREAD

**Issue by aaron-brown** [budjb/grails-rabbitmq-native#47]
In certain circumstances, the RabbitConsumer appears to silently fail without throwing an Exception.

A reproducable state of this issue will be provided soon.

**Comment by budjb** [comment]
Still waiting on a method to reproduce this.

**Comment by budjb** [comment]
Nudge. Poke.

**Comment by aaron-brown** [comment]
[Pong](https://github.com/aaron-brown/RabbitMqNativeSilentFailure)

The error is a StackOverflowError, not so silent in this version of the Plugin (if that changed from ```2.0.10```).

**Comment by budjb** [comment]
Thanks Aaron, all fixed up.

**Comment by budjb** [comment]
This has been fixed in the 3.1 release.
