### ISSUE TITLE
Plugin doesn't allow individual consumer to be shutdown or restarted

### ISSUE THREAD

**Issue by john-london** [budjb/grails-rabbitmq-native#49]
Applications will often have multiple consumers in order to separate responsibilities.  Each consumer may connect to the same RMQ broker.  At present, it is not possible to start/stop individual consumers, instead the whole RMQ context is shutdown and needs to be restarted when RMQ should be turned back on.

Here is existing code that accomplishes this:

    class RmqControllerService {

		boolean shouldRmqBeRunning = false
		def rabbitContext

		/**
		 * Starts all RMQ consumers
		 * @return
		 */
		def startRmqConsumers() {
			shouldRmqBeRunning = true
			rabbitContext = rabbitContext ?: Holders.findApplicationContext()?.getBean('rabbitContext')
			def grailsApp = Holders.getGrailsApplication()
			def rmqPlugin = Holders.getPluginManager().getGrailsPlugin('rabbitmqNative').getInstance()

			rmqPlugin.restartRabbitContext(grailsApp, rabbitContext)
			rabbitContext.startConsumers()
		}

		/**
		 * Stops all RMQ consumers
		 * @return
		 */
		def stopRmqConsumers() {
			shouldRmqBeRunning = false
			rabbitContext = rabbitContext ?: Holders.findApplicationContext()?.getBean('rabbitContext')
			rabbitContext.stopConsumers()
		}

		/**
		 * Return desired status value of RMQ system 
		 * @return True if RMQ should be running, otherwise false
		 */
		boolean shouldRmqBeRunning() {
			return shouldRmqBeRunning
		}
    }

Presently, the only way to have multiple consumers within an application and to stop one from consuming is to have a shouldProcessMessage variable within the consumer that will repeatedly Nack a received message until the variable is set.

**Comment by budjb** [comment]
I'm trying to understand what you're explaining.  You mentioned that consumers will all connect to the same rabbitmq broker.  The broker is the rabbitmq server itself, so do you mean that multiple consumers will connect to the same queue?

If so, why would you have several consumers that act differently on the same messages listen to the same queue?  It seems an exchange could be used that queues get bound to and messages get routed to a consumer based on what action you are trying to take.

For example, we have a process split into 8 stages.  To implement the seperation of responsibilities, we have an exchange that we bind 8 queues to.  It's a direct exchange, and each queue is bound with a certain routing key that dictates what queue (and hence action) is taken on that message.  All messages get published to the exchange, and the consumer appropriate for the action receives the message.

Have I misunderstood?

**Comment by john-london** [comment]
Sorry, it may be me misunderstanding how to use the plugin: assume 2 Consumers within a single Grails app, ConsumerA and ConsumerB.  Both are to connect to Broker.  ConsumerA will be listening to QueueA (or to ExchangeE, with RoutingKeyA), and ConsumerB will be listening to QueueB (or to ExchangeE, with RoutingKeyB).

When the application launches, all consumers defined within the app start to consumer messages, unless rabbitmq.enabled = false within config.groovy.in which case neither consumer will consume messages.

The user should be able to start ConsumerA without ConsumerB starting too.  At a given point, it should be possible to start ConsumerB (and to subsequently shut it down too), without affecting ConsumerA - ConsumerA should continue to consume messages.

(Perhaps this is possible, in which case it's my fault for not understanding how to achieve this, but for the life of me I can't work out how to do this).

**Comment by budjb** [comment]
Ok, I follow your premise now.  Why would you want one consumer to be consuming and another to not be?

**Comment by john-london** [comment]
We have an instance that needs to periodically perform an update of a database that takes quite some time to perform (several hours).  Problems with the load should be transmitted to RMQ for logging and health monitoring purposes and likewise for monitoring for other events of note that appear on the RMQ bus (ConsumerA).  During this time, ConsumerB shouldn't be consuming - we want to turn off ConsumerB.  We're working around this by just NACKing ConsumerB's messages, but this means that there is significant processing power being devoted just to handling the messages - it would be a great improvement to be able to turn B on and off at will.

**Comment by budjb** [comment]
Ok, I'll see what I can do.

**Comment by johnlondon** [comment]
That's awesome, thank you very much - please let me know if I can help.

**Comment by budjb** [comment]
Just a note, this feature is nearing completion.

**Comment by johnlondon** [comment]
Thank you very much, very much appreciated!

Date: Sun, 1 Mar 2015 19:29:53 -0800

**Comment by budjb** [comment]
This feature is complete and will be included in the next release.
