### ISSUE TITLE
Incorrect import path in docs

### ISSUE THREAD

**Issue by michaelrice** [budjb/grails-rabbitmq-native#51]
http://budjb.github.io/grails-rabbitmq-native/doc/manual/guide/converters.html

Says to ```import com.budjb.rabbitmq.converter.MessageConverter```

But the actual path should be ```import com.budjb.rabbitmq.MessageConverter```

**Comment by budjb** [comment]
The package of that class changed with the 3.0.3 release.  The docs on the github pages site reflect the latest version.  Versions 2.0.x do have the package for that class that you mentioned.
