### ISSUE TITLE
Redeliver

### ISSUE THREAD

**Issue by tamershahin** [budjb/grails-rabbitmq-native#53]
Hi Bud,

I'm using your plugin and it's great.. much better that the previous one!
As the previous one though it's not supporting to redeliver of the message X number of times, and it's ok since it's something missing from AMQP protocol.

But i need that feature, and as this answer suggested:
http://stackoverflow.com/a/23161921/3074089

I've created a couple of methods to handle the redelivery a fixed number of time with and exponentially growing waiting time.

It would be great if you could take a look at them and the example grails project I created:

https://github.com/tamershahin/grails-rabbitmq-retry/blob/master/src/groovy/org/gametube/retry/RetryHandler.groovy

I think that running the integration test provided should be enough to understand all logic, let me know if you need any more explanation about that.

The real question is:
I would like to see this feature in the plugin itself, and I'm happy to create that code (I see this feature coded in ConsumerAdapter) and make a pull request. What do you think?
I know that it's not in the protocol specification, so maybe you'll not be inclined to insert it in the plugin.
But it's something very useful, in fact it's the second time i have to introduce this feature in the project i'm working on using RabbitMQ and I would like to avoid customisations or to extend your plugin only for this..

Let me know your thoughts and thanks for all your work.

Tamer

**Comment by tamershahin** [comment]
Hi,

Any comment on this?

Thanks

**Comment by budjb** [comment]
I've quickly read through this, but I'm focusing on finishing up some of the other requests before getting too deep into this one.  I'll let you know.

**Comment by tamershahin** [comment]
Ok, Thank you! :)

I just need to know if there are any chances to see it in the plugin any soon, otherwise I have to encapsulate this feature around your plugin in some other way.
As I say I can even implement this for you and create a pull request, just tell me whenever you got time to look at it.


Thanks for your time!
T

**Comment by tamershahin** [comment]
Hi Bud,

Did you have any time to look at this? I just need to know if it's something you're interested to include in the plugin. 
Otherwise I have to take a decision and see whether to fork the plugin (for a private or public plugin based on yours) or keep the behaviour in a trait and share its .jar across all grails app using rabbit in my current project.

As I said, if your interested in the feature I can create the code to be added in the ConsumerAdapter in a couple of days and to a pull request.

Let me know :)

Tamer

**Comment by budjb** [comment]
The feature seems doable enough. Even if it's not part of the amqp spec, it still seems like something that would be convenient and useful for folks.  The part I don't think belongs in the plugin, though, is the delay timer.

The issue I have with with instructing the thread to sleep is that it blocks that consumer thread from picking up another message until the thread awakens.  I'm not sure how to approach that, what are your thoughts?

**Comment by tamershahin** [comment]
I think that the delay timer is useful to avoid to flood rabbitmq server in case of continuos problems with the task. 
I image a task encountering a temporary (let's say for 1/5 mins) db/net/whatever problem: re-enqueueing the task right away will finish the number of tries (maxAttempts ), flooding the server at the same time (if maxAttempts number is high).

But I see your point, putting the thread to sleep will block the consumer, and this could flood the server as well.

What about this logic:

if an exception occurs and there are still attempts{
     // 1 - create a new consumer
     // 2 - perform the sleep 
     // 3 - update the attempts in the message metadata
     // 4 - resend again to itself with previous state
     // 5 - close the current consumer
}    

of course I don't know if 1 and 5 is doable with current plugin code, but this will keep the number of available consumer stable and provide the feature in a more 'responsible' way.

is it possible? will be heavy for server to create and destroy consumer that wat? 

what do you think?

**Comment by budjb** [comment]
It doesn't make sense to create a consumer for this work since it won't
actually be responsible for consuming any messages.  This is a great use
case for a thread.

The basic flow would be like this:
1. If consumer is configured for retries, a failure occurs, and additional
   retries are available, create a new runnable, passing the required bits to
   (eventually) send the message out.
2. The runnable is run in a new thread.
3. The runnable sleeps for the configured amount of time
4. Message is re-sent.
5. Thread terminates.

This would allow the consumer to continue consuming other messages while
the failed messages waits to resend.  Thoughts?

**Comment by tamershahin** [comment]
about this:
"It doesn't make sense to create a consumer for this work since it won't
actually be responsible for consuming any messages" -> the new consumer will be available for all other tasks in the queue, not for the thread handling the exception (thus preparing to sleep). The current thread/consumer already got all the 'required bits' (aka the context) to send the message out. Then it can die (as thread/consumer since it has create its replacement (the new one in point 1)).

Am I wrong?

In any case your flow will work, I guess. Maybe we can use GPars directly, Grails Promise are for a different purpose (if I remember well..)

**Comment by tamershahin** [comment]
Hi Bud,
I got some free time in the next days and I'll try to implement the solution with a new thread as you suggested.
I'll do it in the github project I used to show you my proposal, if you have any suggestion or if you want to proceed in a different way let me know.

**Comment by tamershahin** [comment]
Hi Bud,

I've created into my project the runnable as discussed:

https://github.com/tamershahin/grails-rabbitmq-retry/blob/master/src/groovy/org/gametube/retry/RabbitRetryRunnable.groovy

that will sleep and then send again the message to the consumer.

I'm delegating thread handling to a threadPool, I guess it's the better approach. If you see any better implementation let me know.

T

**Comment by tamershahin** [comment]
Hi Bud,

Any news on this? I imagine you've been busy.. if you prefer I'll adapt the demo code to the plugin directly in order to create a pull request. Will this be faster for you?

T

**Comment by budjb** [comment]
I am working on a change to how consumers are defined which will fit with this kind of functionality.  It's in progress still, but I'll update when it's complete.

**Comment by dementiev** [comment]
Was this feature finally added to the plugin?
