### ISSUE TITLE
Problem with @Transactional

### ISSUE THREAD

**Issue by davidsawyer** [budjb/grails-rabbitmq-native#55]
I have a consumer whose `handleMessage` contents needed to be wrapped in a `withTransaction { ... }` block. I did that, and everything worked perfectly.

In order to clean that up a little bit, though, I tried adding the `@Transactional` annotation to the class. However, when I start up my app, I get `unable to retrieve configuration for consumer MyConsumer...`. My app starts up completely afterwards, but that consumer won't receive messages.

Not totally sure what could be causing that error. Would you have any ideas and/or solutions?

**Comment by budjb** [comment]
I'll have to write up a test for this and see if I can reproduce it.  I'll let you know.

**Comment by davidsawyer** [comment]
Thanks!

**Comment by budjb** [comment]
I was able to reproduce and fix.  This will go out in the next release.

**Comment by davidsawyer** [comment]
Awesome! Thanks for this.

**Comment by budjb** [comment]
Sure thing.
