### ISSUE TITLE
Publish Expiration Use

### ISSUE THREAD

**Issue by mdsettles** [budjb/grails-rabbitmq-native#56]
Hi,
I am trying to use the expiration parameter on a publish with a Date object as follows:

```
    def now = new Date()
    def expirationDate
    use(TimeCategory) {
        expirationDate = now + 2.days
    }

    // Send the message
    rabbitMessagePublisher.send {
        exchange = RABBITMQ_DIRECT_EXCHANGE_NAME
        routingKey = SEND_QUEUE_PRIORITY_1
        expiration = expirationDate
        body = payload.toString()
    }
```

That results in the following exception:
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - invalid expiration 'Sat Apr 11 13:55:14 MDT 2015': no_integer, class-id=60, method-id=40)
    at com.rabbitmq.client.impl.AMQChannel.processShutdownSignal(AMQChannel.java:270)
    at com.rabbitmq.client.impl.ChannelN.startProcessShutdownSignal(ChannelN.java:261)
    at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:566)
    at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:505)
    at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:498)
    at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:62)
    at com.budjb.rabbitmq.publisher.RabbitMessagePublisherImpl.send(RabbitMessagePublisherImpl.groovy:82)
    at com.budjb.rabbitmq.publisher.RabbitMessagePublisherImpl.send(RabbitMessagePublisherImpl.groovy:93)

The example in the documentation shows only a date without a time.  Does the plugin support a date and time?  How do I convert a Date object to use with the expiration parameter?
Thanks

**Comment by budjb** [comment]
The expiration property is a String, so you'll need to do a `.toString()` or `as String` when setting the property.

**Comment by mdsettles** [comment]
Thanks for the reply!  I love your plugin!

I tried adding toString() as follows:
        rabbitMessagePublisher.send {
            exchange = RABBITMQ_DIRECT_EXCHANGE_NAME
            routingKey = SEND_QUEUE_PRIORITY_1
            expiration = expirationDate.toString()
            body = payload.toString()
        }

However, still the same exception.  Notice that the exception states "no_integer".

**Comment by budjb** [comment]
Ah, I missed that initially. According to AMQP docs for TTL...

> A TTL can be specified on a per-message basis, by setting the expiration field in the basic AMQP class when sending a basic.publish.
> 
> The value of the expiration field describes the TTL period in milliseconds. The same constraints as for x-message-ttl apply. Since the expiration field must be a string, the broker will (only) accept the string representation of the number.

So passing a date will not work (since it's a duration).  Honestly this value should be a long or integer, but AMQP specifies that it's a string of a long or integer.  I can add some convenience methods here to account for that.  Looks like we'll both need some code changes.

Oh, and I'm glad you find this plugin useful!

**Comment by mdsettles** [comment]
OK, thanks for explaining.

**Comment by budjb** [comment]
Does this resolve your issue?

**Comment by mdsettles** [comment]
Yes, this issue is resolved.  When we use an integer duration, it works fine.  Thanks for the help!

**Comment by budjb** [comment]
No problem! I'm leaving this open to represent the work for the convenience methods I'm going to add.

**Comment by budjb** [comment]
Convenience methods added in release 3.1.1.
