### ISSUE TITLE
Consumer handleMessage body is empty string

### ISSUE THREAD

**Issue by nolifelover** [budjb/grails-rabbitmq-native#58]
Hi bud, 
I use Grails 2.3.11, plugin version 3.1.0 and RabbitMQ version 3.5.1 and I follow you document at quickstart section http://budjb.github.io/grails-rabbitmq-native/doc/manual/guide/quickstart.html i can send and receive message it work well, but on handleMessage body is empty string. i try send map or other string body is still empty string

def handleMessage(def body, MessageContext context) {
    println body // not print anything
    return "Hello to you, too!"
 }

Thank you.

**Comment by michaelrice** [comment]
Hi @nolifelover do you have the body defined in the controller as shown in the example?

**Comment by nolifelover** [comment]
@michaelrice  below is my method to public message. i check message on rabbitmq webui, message payload is empty.
def rpcQueue(){
    log.debug "sending to queue"
    render rabbitMessagePublisher.rpc {
      routingKey = "canteen.transactions.request"
      body = "from trasaction queue"
    }
  }

thank you.

**Comment by budjb** [comment]
I'll take a look.

**Comment by budjb** [comment]
This is quite old. Please reopen if you're still having issues.

**Comment by chka** [comment]
Actually, I still have the problem of getting NULL object for anything that goes into the queue except of integers. 

This is the handler code:

```
def handleMessage(def body, MessageContext messageContext) {
        // TODO: Handle messages
        println ">>>4>>>>Got MQ message: " + body.toString()
    }
```
and I'm using org.grails.plugins:rabbitmq-native:3.4.4 and Grails Version: 3.3.8 (just in case it makes a difference, JVM Version: 1.8.0_181 on linux)
