### ISSUE TITLE
ConsumerManagerImpl throws checked exception undeclared on interface

### ISSUE THREAD

**Issue by LanceZant** [budjb/grails-rabbitmq-native#59]
ConsumerManagerImpl.createContext() throws MissingConfigurationException not declared on the ConsumerManager interface.  Not sure if MissingConfigurationException should extend RuntimeException, the interface should declare it, or if the throws clause is just obsolete, but it's scaring our IDEs, and therefore some of our developers. (version 3.1.0)

**Comment by budjb** [comment]
No problem, I'll get this updated.

**Comment by budjb** [comment]
This has been updated in release 3.1.1.
