### ISSUE TITLE
2.0.6 version of the update to 3.1.0

### ISSUE THREAD

**Issue by dudulive** [budjb/grails-rabbitmq-native#60]
I am updating the plugin grails-rabbitmq-native version 2.0.6 to 3.1.0 and am having the following problem when climbing the application:

I have a Consumer seen the import of MessageContext changed and so did the change, there is another change needed, use the Grails 2.1.4?

**Comment by dudulive** [comment]
Forgets to put the error here is:
Error |
2015-05-27 16:50:15,181 [localhost-startStop-1] ERROR context.GrailsContextLoader  - Error executing bootstraps: No such field: rabbitmq for class: com.budjb.rabbitmq.connection.ConnectionBuilderImpl
Message: No such field: rabbitmq for class: com.budjb.rabbitmq.connection.ConnectionBuilderImpl
    Line | Method
->>  115 | doCall                 in Config$_run_closure2_closure9

---

|     64 | loadConnectionContexts in com.budjb.rabbitmq.connection.ConnectionBuilderImpl
|    155 | load . . . . . . . . . in com.budjb.rabbitmq.connection.ConnectionManagerImpl
|     53 | load                   in com.budjb.rabbitmq.RabbitContextImpl
|     58 | load . . . . . . . . . in com.budjb.rabbitmq.RabbitContextProxy
|    188 | doCall                 in RabbitmqNativeGrailsPlugin$_closure2
|    262 | run . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker              in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run                    in java.lang.Thread

**Comment by michaelrice** [comment]
Hi @dudulive did you see this: http://budjb.github.io/grails-rabbitmq-native/doc/manual/guide/upgrading.html#from_2_0_x

**Comment by budjb** [comment]
It looks like there may be a problem in your configuration for rabbitmq.
Can you post the relevant portion of your configuration, with hosts and
credentials removed?

**Comment by dudulive** [comment]
Here is the configuration of the Config.groovy Moved and in development and production server and another:

rabbitmq.server="localhost";
rabbitmq.userName="sednet";
rabbitmq.userPwd="Sde!23";

environments {
    production {
        grails.aplicacao.desenvolvimento=false;
        weakssl.trustedhosts = ['10.5.30.119', '10.5.30.118']; 

```
    rabbitmq.server="10.5.30.118";
}
homolog {
    grails.aplicacao.desenvolvimento=false;
    weakssl.trustedhosts = ['sic-s-lion-o']; // permite a comunicação entre aplicações em servidores que não possuem certificado válido
}
development {
    sPathConfigs = "..\\configs";
    grails.aplicacao.desenvolvimento=false;
    weakssl.trustedhosts = ['localhost', '127.0.0.1']; 
}
test {
    sPathConfigs = "C:\\SIC\\trunk";
    grails.aplicacao.desenvolvimento=false;
    weakssl.trustedhosts = ['localhost', '127.0.0.1', 'gyn028060', 'brg303fc871']; 
}
```

}

rabbitmq {
    connection = {
        connection (host: "${rabbitmq.server}",
                username: "${rabbitmq.userName}",
                password: "${rabbitmq.userPwd}",
                automaticReconnect: true)
    }
}

**Comment by dudulive** [comment]
Was solved was so add the word reserve in this connection settings.

**Comment by budjb** [comment]
Closing this since the problem was already found and fixed.
