### ISSUE TITLE
unable to resolve class RabbitMessagePublisher

### ISSUE THREAD

**Issue by sophiaraw** [budjb/grails-rabbitmq-native#62]
I am using:
Grails 3.0.1
JDK 1.7
rabbitmq-native 3.1.1

---

build.gradle

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-dependencies"
    compile "org.grails:grails-web-boot"
    compile "org.grails.plugins:hibernate"
    compile "org.grails.plugins:cache"
    compile "org.hibernate:hibernate-ehcache"
    compile "org.postgresql:postgresql:9.4-1201-jdbc41"
    compile "org.grails.plugins:quartz:2.0.0.M4"
    compile "org.grails.plugins:mail:2.0.0.RC1"
    compile "org.grails.plugins:rabbitmq-native:3.1.1"
    compile 'joda-time:joda-time:2.7'
    compile "org.codehaus.groovy.modules.http-builder:http-builder:0.7"
    runtime "org.grails.plugins:asset-pipeline"
    runtime "org.grails.plugins:scaffolding"
    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"
    // Note: It is recommended to update to a more robust driver (Chrome, Firefox etc.)
    testRuntime 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0'
    console "org.grails:grails-console"
}

---

In my groovy class, I am trying to use the  RabbitMessagePublisher class
import com.budjb.rabbitmq.publisher.*

But I am getting the following error: unable to resolve class RabbitMessagePublisher

The plugin does appear in my External Libraries on my project.

Please can you point me in the right direction.
Regards
Sophia

**Comment by budjb** [comment]
This plugin is only for Grails 2.x.  Given the massive changes to Grails 3.0 and up, this plugin will not work with those versions.

I have started work on converting this plugin to a Grails 3 plugin.  I'll update when it's complete.

**Comment by jakon89** [comment]
Hi
First: Thanks for providing awesome plugin! It's suer usefull and easy to use.

When will it work with grails 3?
I can help if you have for example todo list etc.

Regards, Adam

**Comment by budjb** [comment]
Closing this as a duplicate at this point.  See #70 for updates.
