### ISSUE TITLE
Optionally consumers starting

### ISSUE THREAD

**Issue by jakon89** [budjb/grails-rabbitmq-native#67]
Hi,
I wonder why Consumers are not loading when system starts.
I spent about 15 hours on research(and learning) in plugin code and I realy don't see any reasons.
I'm talking about 189 line in RabbitmqNativeGrailsPlugin.

However, I did some improvements and plugin successfully works with grails 3. I will make pull request soon.

Can I make my independent fork of this project? I have few ideas which i want provide. 

Regards, Adam

**Comment by budjb** [comment]
Pull requests are welcome.  I see you've sent one in - I'll take a look at it.

The grails 2.x plugin has pulled ahead of the work I've done for 3.x, so I need to get those code changes merged into that branch of code and get it released.

**Comment by budjb** [comment]
Closing this as a duplicate at this point.  See #70 for updates.
