### ISSUE TITLE
dynamic queue

### ISSUE THREAD

**Issue by gomedya** [budjb/grails-rabbitmq-native#71]
hi, in a chat room environment, i'd like to provide private messaging feature, which will require a new queue for each new registered user. however queues are created in 'config.groovy' file and are static. is it possible to create a queue at runtime and do you think this is the right way to go for this scenario. thanks.

**Comment by budjb** [comment]
Sorry for the late response here. Queues are easily created using the RabbitMQ libraries directly. The tricky part here is if you want to use the plugin's consumers to read from those queues. This should be possible, but it will require a lot of use of the backend classes.

My question though is why a queue per chat room?  You can use a topic exchange for this use.  Topic exchanges were made for just this kind of thing.

**Comment by gomedya** [comment]
hi, no problem, thanks for taking time to answer. i gave chatroom example but my real scenario is this. i have a web based ui written in grails where users sign in and start a java jar at the remote machine. output of the java jar (lines of json) is sent back to the ui via a rabbit queue. each user can start the same jar more than once with different parameters. each run is a separate os level process with its unique pid. user can open the ui multiple times at different tabs and start the jar with different parameters and each ui/tab needs to receive only that run's output. so i assume i can use the pid of the background process as an exchange topic or queue name. how would you approach this scenario? thanks.

**Comment by budjb** [comment]
So, single app?

**Comment by gomedya** [comment]
one app for web ui. one app that does the real job.

**Comment by gomedya** [comment]
hi, I still have the problem. I wish to restate the problem at hand. I'd like to remove the queue definition from config.groovy and make it dynamic, defer the creation of queue and make it part of an action. however, when I remove the definition from config.groovy, the app doesn't start saying "unable to start application because the RabbitMQ connection configuration was not found". do I have to define the queue at the very beginning. thanks.

**Comment by budjb** [comment]
Closing this since it's a year old. Reopen if you need more help.
