### ISSUE TITLE
Can't find 3.1.2 in the repos

### ISSUE THREAD

**Issue by robertoschwald** [budjb/grails-rabbitmq-native#75]
Version 3.1.2 is tagged, but cannot be found in grails.org or bintray repos. Only 3.1.2-beta1 is there.

Is tag https://github.com/budjb/grails-rabbitmq-native/releases/tag/3.1.2 not ready, yet?

**Comment by budjb** [comment]
I'm sorry, that was a mistag. The tag 3.1.2 is the beta 1 version, and I've removed that tag and created one under the proper name with the same commit.

Now that I've wrapped up coding on the jaxrs plugin stuff, I'm going to focus on getting a couple of things done in this plugin and release a non-beta version of the plugin.
