### ISSUE TITLE
3.2.0 not tagged

### ISSUE THREAD

**Issue by robertoschwald** [budjb/grails-rabbitmq-native#77]
Figured out that 3.2.0 is released to bintray but it seems it's not tagged in the repo.

**Comment by budjb** [comment]
I can see the tag both in my local clone and in the GitHub UI. Maybe I'm not looking in the same place you are?

**Comment by robertoschwald** [comment]
My bad. GH sorts 3.1.2-beta1 before 3.2.0.

**Comment by budjb** [comment]
👍
