### ISSUE TITLE
Is it possible to have multiple instances of a consumer running?

### ISSUE THREAD

**Issue by PatrickHuetter** [budjb/grails-rabbitmq-native#79]
I would like to have multiple parallel consuming instances for the same type running. Is this possible? If yes, how?

**Comment by budjb** [comment]
http://budjb.github.io/grails-rabbitmq-native/3.x/latest/ref/Consumer%20Configuration/consumers.html

Does that give you what you're looking for?

**Comment by budjb** [comment]
Closing this for now. Reopen if you need more help with this.
