### ISSUE TITLE
Update to amqp-client 3.6.6 when released (fix for not reliably reconnecting some times)

### ISSUE THREAD

**Issue by robertoschwald** [budjb/grails-rabbitmq-native#83]
The amqp client has a bug, which sometimes causes a NPE on reconnect.
It will be fixed with version 2.6.6 (see https://github.com/rabbitmq/rabbitmq-java-client/pull/197)
I tried with 2.6.6-SNAPSHOT, error is gone.

[error removed, as it was an internal Artifactory problem]

**Comment by robertoschwald** [comment]
amqp-client 3.6.6 is released. Please update the dependency.

**Comment by budjb** [comment]
Completed with PR https://github.com/budjb/grails-rabbitmq-native/pull/85
