### ISSUE TITLE
Way to bind consumer to multiple connections

### ISSUE THREAD

**Issue by jprabawa** [budjb/grails-rabbitmq-native#92]
In a multi-server setup, e.g. there are two connections, is there a way to bind a consumer to both connections? 

Or I guess it makes more sense to have an instance of that consumer for each connection.

The doc only seems to support a single connection per consumer: http://budjb.github.io/grails-rabbitmq-native/3.x/latest/ref/Consumer%20Configuration/connection.html Is there a way to avoid making an identical copy of the same consumer class to support multiple connections?

**Comment by budjb** [comment]
I'm just curious what the scenario here is? This sounds like something better suited for the shoveling functionality built into RabbitMQ, but I'd like to understand it.

**Comment by jprabawa** [comment]
Thanks for the reply. I think the use case is atypical of a grails application. Will close this :)
