### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by gomedya** [budjb/grails-rabbitmq-native#95]
hi, i publish a map from a java app as follows, and if i receive it from a java app, i can deserialise to a map again without a problem.

byte[] bytes = SerializationUtils.serialize( map );
channel.basicPublish( exchange, routingKey, props, bytes );

when i receive in grails and if i handle it as a map, it receives the message but does not trigger map handler, because received message is always a string:

def handleMessage(Map msg, MessageContext context) 
{
	println msg
}

ERROR consumer.ConsumerContextImpl  - RabbitConsumer does not have a message handler defined to handle class type class java.lang.String

if i handle a string at grails side, handler gets triggered but i can't deserialise received string to a map. 

same is true, if i send a string from java, i receive extra characters prepended to original string at grails side.

seems like i'm missing something.

**Comment by gomedya** [comment]
if both receiver and sender are grails/groovy there is no problem, string and map gets transferred. if sender is java, problem described above occurs.

**Comment by gomedya** [comment]
deserializing context.body works

**Comment by budjb** [comment]
The built-in map converter converts the map to json and sends as a string. The plugin doesn't have a built-in java serialization/deserialization. I've thought about adding it though.

**Comment by gomedya** [comment]
i think it would be a good addition because the whole idea of using rabbit is integration with other (mostly) java apps. accessing context.body solved my problem but handleMessage(Object.. would be more elegant. thanks tor the answer.

**Comment by budjb** [comment]
I've been working on a bit of a refactor of the conversion system and `Serializable` will be supported.

**Comment by budjb** [comment]
This was added in PR #99 and will be available in version 3.4.
